----==================================================================================
-------------------------------------PROJET BDD SRC-----------------------------------
------------------------------------GROUPE 5 3SRC1-----------------------------------
----------------------------------SUJET:Médiathéque-----------------------------------
----==================================================================================  


---- Création table UTILISATEUR ----
CREATE TABLE UTILISATEUR
(
    ID_UTILISATEUR INT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(3) NOT NULL,
    PRENOM VARCHAR(30) NOT NULL,
    MAIL TEXT NOT NULL,
    ID_COMMUNE INT NOT NULL,
    ID_CATEGORIE_SOCIAL INT NOT NULL
);

---- Création table COMMUNE ----
CREATE TABLE COMMUNE
(
    ID_COMMUNE INT NOT NULL AUTO_INCREMENT,
    VILLE VARCHAR(30) NOT NULL
);

---- Création table CATEGORIE SOCIAL ----
CREATE TABLE CATEGORIE_SOCIAL
(
    ID_CATEGORIE_SOCIAL INT NOT NULL AUTO_INCREMENT,
    CATEGORIE_SOCIAL VARCHAR(30) NOT NULL
);

---- Création table ABONNEMENT ----
CREATE TABLE ABONNEMENT
(
    ID_ABONNEMENT INT NOT NULL AUTO_INCREMENT,
    DEBUT_ADHESION DATE NOT NULL,
    FIN_ADHESION DATE NULL,
    ID_UTILISATEUR INT NOT NULL,
    ID_TYPE_ABONNEMENT INT NOT NULL

);

---- Création table TYPE ABONNEMENT ----
CREATE TABLE TYPE_ABONNEMENT
(
    ID_TYPE_ABONNEMENT INT NOT NULL AUTO_INCREMENT, 
    PRIX_PAR_MOIS FLOAT NOT NULL,
    NOMBRE_EMPUNT INT NOT NULL
);


---- Création table EMPRUNT   ----
CREATE TABLE EMRUNT
(
    ID_EMPRUNT INT NOT NULL AUTO_INCREMENT,
    DATE_EMPRUNT DATE NOT NULL,
    ID_ABONNEMENT INT NOT NULL,
);

---- Création table RETOUR   ----
CREATE TABLE RETOUR
(
    ID_RETOUR INT NOT NULL AUTO_INCREMENT,
    RETOUR_DATE_RENDU DATE NOT NULL
);


---- Création table OBJET   ----
CREATE TABLE OBJET
(
    ID_OBJET INT NOT NULL AUTO_INCREMENT,
    NOMBRE_ARTICLE INT NOT NULL,
    PRIX_OBJET FLOAT NOT NULL, 
    ID_PENALITE INT NOT NULL
);

---- Création table PENALITE   ----
CREATE TABLE PENALITE
(
    ID_PENALITE INT NOT NULL AUTO_INCREMENT,
    TYPE_OBJET VARCHAR (30) NOT NULL,
    PRIX_J_PENALITER FLOAT NOT NULL
);
---- Création table RETOUR   ----
CREATE TABLE RENDRE
(
    ID_RETOUR INT NOT NULL,
    ID_OBJET INT NOT NULL
);

CREATE TABLE RETOURNER
(
    ID_RETOUR INT NOT NULL,
    ID_EMPRUNT INT NOT NULL
);

---- Création table EMPRUNTER   ----
CREATE TABLE EMPRUNTER
(
    ID_EMPRUNT INT NOT NULL,
    ID_OBJET INT NOT NULL
);

CREATE TABLE CASSETTE
(
    ID_CASSETTE INT NOT NULL AUTO_INCREMENT,
    TITRE_CASSETTE VARCHAR (30) NOT NULL
);

CREATE TABLE VISIONER
(
    ID_CASSETTE INT NOT NULL,
    ID_FILM INT NOT NULL
);

CREATE TABLE FILM
(
    ID_FILM INT NOT NULL AUTO_INCREMENT,
    TITRE VARCHAR (30) NOT NULL
);

CREATE TABLE CATEGORISER
(
    ID_FILM INT NOT NULL,
    ID_GENRE INT NOT NULL
);

CREATE TABLE GENRE
(
    ID_GENRE INT NOT NULL AUTO_INCREMENT,
    GENRE VARCHAR (30) NOT NULL
);

CREATE TABLE CONCEVOIR
(
    ID_FILM INT NOT NULL,
    ID_ARTISTE INT NOT NULL
);

CREATE TABLE JOUER
(
    ID_FILM INT NOT NULL,
    ID_ARTISTE INT NOT NULL
);

CREATE TABLE ARTISTE
(
    ID_ARTISTE INT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR (30) NOT NULL,
    PRENOM VARCHAR (30) NOT NULL
);

CREATE TABLE PRODUIRE
(
    ID_MUSIQUE INT NOT NULL,
    ID_ARTISTE INT NOT NULL
);

CREATE TABLE COMPOSER
(
    ID_MUSIQUE INT NOT NULL,
    ID_ARTISTE INT NOT NULL
);

CREATE TABLE INTERPRETER
(
    ID_MUSIQUE INT NOT NULL,
    ID_ARTISTE INT NOT NULL
);

CREATE TABLE MUSIC
(
    ID_MUSIQUE INT NOT NULL AUTO_INCREMENT,
    TITRE VARCHAR (30) NOT NULL
);

CREATE TABLE ECOUTER
(
    ID_DISQUE INT NOT NULL,
    ID_MUSIQUE INT NOT NULL
);

CREATE TABLE DISQUES
(
    ID_DISQUE INT NOT NULL AUTO_INCREMENT,
    TITRES_DISQUE VARCHAR (30) NOT NULL
);

---- ADD PRIMARY KEY
ALTER TABLE UTILISATEUR
    ADD PRIMARY KEY (ID_UTILISATEUR);

ALTER TABLE COMMUNE
    ADD PRIMARY KEY (ID_COMMUNE);

ALTER TABLE CATEGORIE_SOCIAL
    ADD PRIMARY KEY (ID_CATEGORIE_SOCIAL);

ALTER TABLE ABONNEMENT
    ADD PRIMARY KEY (ID_ABONNEMENT);

ALTER TABLE TYPE_ABONNEMENT
    ADD PRIMARY KEY (ID_TYPE_ABONNEMENT);

ALTER TABLE EMRUNT
    ADD PRIMARY KEY (ID_EMPRUNT);

ALTER TABLE RETOUR
    ADD PRIMARY KEY (ID_RETOUR);

ALTER TABLE OBJET
    ADD PRIMARY KEY (ID_OBJET);

ALTER TABLE PENALITE
    ADD PRIMARY KEY (ID_PENALITE);

ALTER TABLE RENDRE
    ADD PRIMARY KEY (ID_RETOUR,ID_OBJET);

ALTER TABLE RETOURNER
    ADD PRIMARY KEY (ID_RETOUR,ID_EMPRUNT);

ALTER TABLE CASSETTE
    ADD PRIMARY KEY (ID_CASSETTE);

ALTER TABLE VISIONER
    ADD PRIMARY KEY (ID_CASSETTE,ID_FILM);

ALTER TABLE FILM
    ADD PRIMARY KEY (ID_FILM);

ALTER TABLE CATEGORISER
    ADD PRIMARY KEY (ID_FILM,ID_GENRE);

ALTER TABLE GENRE
    ADD PRIMARY KEY (ID_GENRE);

ALTER TABLE CONCEVOIR
    ADD PRIMARY KEY (ID_FILM,ID_ARTISTE);

ALTER TABLE JOUER
    ADD PRIMARY KEY (ID_FILM,ID_ARTISTE);

ALTER TABLE JOUER
    ADD PRIMARY KEY (ID_FILM,ID_ARTISTE);

ALTER TABLE ARTISTE
    ADD PRIMARY KEY (ID_ARTISTE);

ALTER TABLE PRODUIRE
    ADD PRIMARY KEY (ID_MUSIQUE,ID_ARTISTE);

ALTER TABLE COMPOSER
    ADD PRIMARY KEY (ID_MUSIQUE,ID_ARTISTE);

ALTER TABLE INTERPRETER
    ADD PRIMARY KEY (ID_MUSIQUE,ID_ARTISTE);

ALTER TABLE MUSIC
    ADD PRIMARY KEY (ID_MUSIQUE);

ALTER TABLE ECOUTER
    ADD PRIMARY KEY (ID_MUSIQUE,ID_DISQUE);

ALTER TABLE DISQUES
    ADD PRIMARY KEY (ID_DISQUE);